[tool.poetry]
name = "executor"
version = "0.1.0"
description = "Enqueues sim runs"
authors = ["Five Grant <five@jataware.com>"]
readme = "README.md"
packages = [{include = "api"}, {include="tests"}]
license = "MIT"


[tool.poetry.urls]
"Bug Tracker" = "https://github.com/DARPA-ASKEM/askem-simulation-service/issues"


[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
pandas = "^1.5.2"
pydantic = "^1.10.2"
requests = "^2.28.1"


[tool.poetry.group.api.dependencies]
uvicorn = "^0.19.0"
fastapi = "^0.85.1"
julia = "^0.6.1"
rq = "^1.13.0"
redis = "^4.5.1"
pyarrow = "^10.0.0"
fsspec = "^2022.11.0"
python-multipart = "^0.0.5"
s3fs = "^2022.11.0"
botocore = "1.27.59"
boto3 = "1.24"
minio = "^7.1.13"


[tool.poetry.group.dev.dependencies]
isort = "^5.10.1"
black = "^22.10.0"
pylint = "^2.15.5"
pytest = "^7.2.0"
pre-commit = "^2.20.0"


[tool.poetry.scripts]
executor = "api.main:cli"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[virtualenvs]
in-project = true


[tool.isort]
profile = "black"


[tool.pytest.ini_options]
python_files = ["tests/*.py"]


[tool.pylint.master]
# Since the data store is part of an R&D project, it makes sense to move fast
# and leave TODOs for later.
disable=["fixme", "too-few-public-methods"]
# Pylint should not run on the the generated files
extension-pkg-whitelist=["pydantic"]
jobs=4


[tool.pylint.basic]
good-names=["id", "type"]


[tool.pylint.variables]
allowed-redefined-builtins=["id", "type"]


[tool.pylint.format]
max-line-length=88
