version: "3.9"
networks:
  sim-execution:
    driver: bridge
    name: sim-execution
services:
  api:
    container_name: executor-api
    build: 
      context: ../
      dockerfile: docker/Dockerfile.api
    ports:
      - "9090:9090"
    env_file:
      - ../config.env
    networks:
      - sim-execution
  rqworker:
    container_name: rqworker
    build: 
      context: ../
      dockerfile: docker/Dockerfile.worker
    env_file:
      - ../config.env
    networks:
      - sim-execution
  redis:
    container_name: redis
    image: redis
    networks:
      - sim-execution
    ports:
    - mode: ingress
      target: 6379
      published: "6379"
      protocol: tcp
