version: "3.9"
networks:
  sim-execution:
    driver: bridge
    name: sim-execution
services:
  api:
    container_name: scheduler
    build: 
      context: ../
      dockerfile: docker/Dockerfile.api
    ports:
      - "8080:8080"
    networks:
      - sim-execution
