---
# Automatically build Docker images on changes to main and push them to a
# Container Registry using HCL Bake file.

name: Build Docker Images
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ['main']
    tags: ['*']

jobs:
  # Generate a more robust tag for the image
  tag-generator:
    name: Determine image tag
    runs-on: ubuntu-22.04
    outputs:
      image-tag: ${{ steps.generate.outputs.tag }}
    steps:
      - name: Generate appropriate tag
        id: generate
        run: |
          if [[ '${{ github.ref_type }}' == 'branch' && '${{ github.ref_name }}' == 'main' ]]; then
            TAG=latest
          else
            SEMVER=$( echo ${{ github.ref_name }} | sed -nre 's/^v[^0-9]*(([0-9]+\.)*[0-9]+(-[a-z]+)?).*/\1/p')
            if [[ -n $SEMVER ]]; then
              TAG=${SEMVER}
            else
              TAG=${{ github.ref_name }}
            fi
          fi
          echo "$TAG"
          echo "tag=${TAG,,}" >> ${GITHUB_OUTPUT}
      - name: Show Generated Tag
        run: echo ${{ steps.generate.outputs.tag }}

  # Build and Publish all targets associated with specified group
  bake:
    needs:
      - tag-generator
    uses: darpa-askem/.github/.github/workflows/bake-publish.yml@main
    with:
      file: 'docker/docker-bake.hcl'
      group: 'prod'
      registry: 'ghcr.io'
      organization: ${{ github.repository_owner }}
      tag: ${{ needs.tag-generator.outputs.image-tag }}
    secrets:
      username: ${{ github.repository_owner }}
      password: ${{ secrets.GITHUB_TOKEN }}

  # Execute simulation-integration reporting
  simulation-integration:
    runs-on: ubuntu-latest
    needs: 
      - bake
    steps:
      - name: Report
        env: 
          GITHUB_TOKEN: ${{ secrets.GHP_ACCESS_TOKEN }}
        run: |
          gh workflow run report.yaml --repo DARPA-ASKEM/simulation-integration --ref main
